Controllers/EmployeeController.cs
using ExpenseApplication.Models;
using ExpenseApplication.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ExpenseApplication.Utilities;
using Newtonsoft.Json;
using ExpenseApplication.Filters;
using ExpenseApplication.Repositories;
using ExpenseApplication.Interfaces;

namespace ExpenseApplication.Controllers
{
    [EmployeeAuthFilter]
    public class EmployeeController : Controller
    {
        private IEmployee empRepository;

        public EmployeeController()
        {
            this.empRepository = new EmployeeRepository(new ExpenseDbContext());
        }

        public ActionResult AddExpense()
        {
            var model = new ExpenseFormViewModel
            {
                DateSubmitted = DateTime.Now,
                Expenses = new List<ExpenseViewModel>(),
                CurrencyList = Enum.GetValues(typeof(Currency)).Cast<Currency>()
                           .Select(c => new SelectListItem
                           {
                               Value = c.ToString(),
                               Text = c.ToString()
                           })
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddExpense(ExpenseFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int userId = Convert.ToInt32(Session["UserId"]);

                    ExpenseForm form = new ExpenseForm
                    {
                        UserId = userId,
                        Currency = model.Currency,
                        DateSubmitted = DateTime.Now,
                        Expenses = model.Expenses.Select(e => new Expense
                        {
                            Description = e.Description,
                            ExpenseDate = e.ExpenseDate,
                            Amount = e.Amount
                    
                        }).ToList(),
                        TotalAmount = model.Expenses.Sum(e => e.Amount),
                        Status = ExpenseFormStatus.PendingApproval
                    };

                    empRepository.AddExpense(form);

                    var history = new ExpenseFormHistory()
                    {
                        ExpenseFormId = model.Id,
                        ChangeDate = DateTime.Now,
                        OldStatus = ExpenseFormStatus.PendingApproval,
                        NewStatus = ExpenseFormStatus.PendingApproval,
                        Remarks = "No Remarks Yet",
                        ActionBy= Session["UserName"].ToString()

                    };

                    empRepository.AddExpenseFormHistory(history);
                    empRepository.SaveChanges();

                    TempData["SweetAlertMessage"] = "Expenses Added successfully!";
                    TempData["SweetAlertType"] = "success";
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    Log.Error("Error adding expense form: ", ex);
                    TempData["SweetAlertMessage"] = "An error occurred while adding the expense form.";
                    TempData["SweetAlertType"] = "error";
                    return RedirectToAction("Index", "Home");
                }
            }

            model.CurrencyList = GetCurrencyList();
            return View(model);
        }

        public ActionResult ExpenseDetails(int id)
        {
            try
            {
                var form = empRepository.GetExpenseFormById(id);
                if (form == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var latestHistory = form.History.OrderByDescending(h => h.ChangeDate).FirstOrDefault();

                var viewModel = new ExpenseFormDetailsViewModel
                {
                    ExpenseForm = form,
                    LatestRemark = latestHistory != null ? latestHistory.Remarks : "No Remarks Available"
                };

                return View(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error("Error fetching expense details: ", ex);
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                var form = empRepository.GetExpenseFormById(id);
                if (form == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                if (form.Status == ExpenseFormStatus.Approved || form.Status == ExpenseFormStatus.Paid)
                {
                    return RedirectToAction("Index", "Home");
                }

                var viewModel = new ExpenseFormViewModel
                {
                    Id = form.Id,
                    UserId = form.UserId,
                    Currency = form.Currency,
                    DateSubmitted = form.DateSubmitted,
                    TotalAmount = form.TotalAmount,
                    Expenses = form.Expenses.Select(e => new ExpenseViewModel
                    {
                        Description = e.Description,
                        ExpenseDate = e.ExpenseDate,
                        Amount = e.Amount
                    }).ToList(),
                    CurrencyList = GetCurrencyList()
                };

                return View(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error("Error fetching expense form for editing: ", ex);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Edit(ExpenseFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Log.Info(JsonConvert.SerializeObject(model));
                    var form = empRepository.GetExpenseFormById(model.Id);
                    if (form == null)
                    {
                        return HttpNotFound();
                    }

                    form.Currency = model.Currency;
                    form.TotalAmount = model.Expenses.Sum(e => e.Amount);
                    form.DateSubmitted = DateTime.Now;

                    empRepository.RemoveExpenses(form.Expenses.ToList());

                    foreach (var expense in model.Expenses)
                    {
                        var newExpense = new Expense
                        {
                            Description = expense.Description,
                            ExpenseDate = expense.ExpenseDate,
                            Amount = expense.Amount
                        };

                        form.Expenses.Add(newExpense);
                    }

                    var latestHistory = form.History.OrderByDescending(h => h.ChangeDate).FirstOrDefault();
                    var history = new ExpenseFormHistory()
                    {
                        ExpenseFormId = form.Id,
                        ChangeDate = DateTime.Now,
                        OldStatus = latestHistory.NewStatus,
                        NewStatus = latestHistory.NewStatus,
                        Remarks = "Form Editted by Employee",
                        ActionBy = Session["UserName"].ToString()
                    };
                    empRepository.AddExpenseFormHistory(history);
                    empRepository.SaveChanges();

                    TempData["SweetAlertMessage"] = "Expenses Edited successfully!";
                    TempData["SweetAlertType"] = "success";

                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    Log.Error("Error editing expense form: ", ex);
                    TempData["SweetAlertMessage"] = "An error occurred while editing the expense form.";
                    TempData["SweetAlertType"] = "error";
                    return RedirectToAction("Index", "Home");
                }
            }

            model.CurrencyList = GetCurrencyList();
            return View(model);
        }

        private IEnumerable<SelectListItem> GetCurrencyList()
        {
            return new List<SelectListItem>
            {
                new SelectListItem { Value = "USD", Text = "USD" },
                new SelectListItem { Value = "EUR", Text = "EUR" },
                new SelectListItem { Value = "TL", Text = "TL" },
                new SelectListItem { Value = "PKR", Text = "PKR" },
                new SelectListItem { Value = "INR", Text = "INR" }
            };
        }
    }
}

Controllers/ManagerController.cs
using ExpenseApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ExpenseApplication.Utilities;
using Newtonsoft.Json;
using ExpenseApplication.Models.ViewModels;
using ExpenseApplication.Filters;
using ExpenseApplication.Interfaces;
using ExpenseApplication.Repositories;

namespace ExpenseApplication.Controllers
{
   [ManagerAuthFilter]
    public class ManagerController : Controller
    {

        private IManager manRepository;

        public ManagerController()
        {
            this.manRepository = new ManagerRepository(new ExpenseDbContext());
        }
        public ActionResult ExpenseForms(int id, string dateFrom, string dateTo, string amountRange)
        {
            Log.Info("Amount " + amountRange);
            var userId = Convert.ToInt32(Session["UserId"]);

            //check if loggedin user(manager) is same as for whom the expense forms are to be found
            if (userId != id)
            {
                return RedirectToAction("Index","Home");   
            }

            try
            {
                // Fetch the manager and their employees
                var manager = manRepository.GetEmployeesUnderManager(id);

                if (manager == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var employeeExpenseForms = manRepository.GetExpenseForms(manager);

                if (!string.IsNullOrEmpty(dateFrom))
                {
                    DateTime DateFrom;
                    if (DateTime.TryParse(dateFrom, out DateFrom))
                    {
                        employeeExpenseForms = employeeExpenseForms.Where(f => f.DateSubmitted >= DateFrom.Date);
                    }
                }


                if (!string.IsNullOrEmpty(dateTo))
                {
                    DateTime DateTo;
                    if (DateTime.TryParse(dateTo, out DateTo))
                    {
                        DateTo = DateTo.AddDays(1);
                        employeeExpenseForms = employeeExpenseForms.Where(f => f.DateSubmitted <= DateTo);
                    }
                }

                if (!string.IsNullOrEmpty(amountRange))
                {
                    if (int.TryParse(amountRange, out int AmountRange))
                    {
                        employeeExpenseForms = employeeExpenseForms.Where(f => f.TotalAmount <= AmountRange);
                    }
                }

                    return View(employeeExpenseForms.ToList());

            }
            catch (Exception ex)
            {
                Log.Error("Error editing expense form: ", ex);
                TempData["SweetAlertMessage"] = "An error occurred fetching the expense forms.";
                TempData["SweetAlertType"] = "error";
                return RedirectToAction("Index", "Home");
            }
 

        }

        public ActionResult ChangeStatus(int id)
        {
            try
            {
                var form = manRepository.GetExpenseFormDetails(id);

                if (form == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                var latestHistory = form.History.OrderByDescending(h => h.ChangeDate).FirstOrDefault();
                var viewModel = new ExpenseFormDetailsViewModel
                {
                    ExpenseForm = form,
                    LatestRemark = latestHistory != null ? latestHistory.Remarks : "No Remarks Available" //To display in UI
                };

                return View(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error("Error editing expense form: ", ex);
                TempData["SweetAlertMessage"] = "An error occurred while fetching the expense form.";
                TempData["SweetAlertType"] = "error";
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult Edit(int id)
        {
            try
            {


                var form = manRepository.GetExpenseForm(id);
                if (form == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var latestHistory = form.History.OrderByDescending(h => h.ChangeDate).FirstOrDefault();

                var viewModel = new ChangeStatusViewModel
                {
                    ExpenseForm = form,
                    Remarks = latestHistory != null ? latestHistory.Remarks : "No Remarks Available"
                };

                return View(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error("Error editing expense form: ", ex);
                TempData["SweetAlertMessage"] = "An error occurred while fetching the expense form for editing.";
                TempData["SweetAlertType"] = "error";
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Edit(ChangeStatusViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                Log.Info("Remarks: "+model.Remarks);

                var form = manRepository.GetExpenseForm(model.ExpenseForm.Id);
                if (form != null)
                {
                    form.Status = model.ExpenseForm.Status;
                    manRepository.SaveChanges();
                    var FormHistory = manRepository.GetFormHistory(model.ExpenseForm.Id);

                    var history = new ExpenseFormHistory()
                    {
                        ExpenseFormId = model.ExpenseForm.Id,
                        ChangeDate = DateTime.Now,
                        OldStatus = FormHistory.NewStatus,
                        NewStatus = model.ExpenseForm.Status,
                        Remarks = model.Remarks,
                        ActionBy = Session["UserName"].ToString()
                    };

                    manRepository.AddExpenseFormHistory(history);
                    manRepository.SaveChanges();
                    Log.Info("Form status updated by Manager: " + Session["UserName"]);
                    var userId = Convert.ToInt32(Session["UserId"]);
                    TempData["SweetAlertMessage"] = "Expenses Status Updated Successfully!";
                    TempData["SweetAlertType"] = "success";
                    return RedirectToAction("ExpenseForms", new { id = userId });
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }catch (Exception ex)
            {
                Log.Error("Error editing expense form: ", ex);
                TempData["SweetAlertMessage"] = "An error occurred while editing the expense form Status.";
                TempData["SweetAlertType"] = "error";
                return RedirectToAction("Index", "Home");
            }
        }

            return View(model);
        }
    }
}

Views/Home/AccoutantHome.cshtml
@model ExpenseApplication.Models.User
@{
    ViewBag.Title = "AccoutantHome";
}

<div class="float-end">@Html.ActionLink("Expense Forms", "ExpenseForms", "Accountant", new { id = Session["UserId"] }, new { @class = "btn btn-primary" })</div>


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white fw-bold">
                    <h4 class="text-center">User Details</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Username: @Model.Username</h5>
                    <p class="card-text">
                        <strong>Email:</strong> @Model.Email<br />
                    </p>

                    <p class="card-text">
                        <strong>Role:</strong> @Model.Role<br />
                    </p>
                </div>

            </div>
        </div>
    </div>
</div>

Views/Home/AdminHome.cshtml
@{
    ViewBag.Title = "Expense Form Status Charts";
}

<h2>Welcome Admin</h2>

<h1 class="text-center fw-bold">Reports</h1>

<div class="container mt-5">
    <div class="row">
        <!-- First Pie Chart for Expense Form Status -->
        <div class="col-md-6">
            <div class="card">
              
                <div class="card-body">
                    <div id="expenseFormStatusChart" style="height: 370px; width: 100%;"></div>
                </div>
            </div>
        </div>

        <!-- Second Chart for EMployees Forms Chart -->
        <div class="col-md-6">
            <div class="card">
               
                <div class="card-body">
                    <div id="employeeFormsChart" style="height: 370px; width: 100%;"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-6">
            <div class="card">

                <div class="card-body">
                    <div id="managerEmployeesChart" style="height: 370px; width: 100%;"></div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <div id="dailyExpenseChart" style="height: 370px; width: 100%;"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5 justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <div id="dailyExpenseChartByCurrency" style="height: 370px; width: 100%;"></div>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script src="https://cdn.canvasjs.com/canvasjs.min.js"></script>

    <script>

    var expenseFormStatusChart = new CanvasJS.Chart("expenseFormStatusChart", {
        theme: "light",
        exportEnabled: true,
        animationEnabled: true,
        title: {
            text: "Expense Form Status Distribution"
        },
        data: [{
            type: "pie",
            startAngle: 180,
            toolTipContent: "<b>{label}</b>: {y}",
            showInLegend: "true",
            legendText: "{label}",
            indexLabel: "{label} - {y}",
            dataPoints: @Html.Raw(ViewBag.DataPoints)
        }]
    });
        expenseFormStatusChart.render();

   var employeeFormChart = new CanvasJS.Chart("employeeFormsChart", {
        theme: "light",
        exportEnabled: true,
        animationEnabled: true,
        title: {
            text: "Number of Forms Submitted by Employees"
        },
        data: [{
            type: "column",
            toolTipContent: "<b>{label}</b>: {y}",
            dataPoints: @Html.Raw(ViewBag.EmployeeFormData)
        }]
    });
        employeeFormChart.render();



        var managerAndEmployeesChart = new CanvasJS.Chart("managerEmployeesChart", {
      theme: "light",
      exportEnabled: true,
      animationEnabled: true,
      title: {
          text: "Number of Employees under Managers"
      },
      data: [{
          type: "column",
          toolTipContent: "<b>{label}</b>: {y}",
          dataPoints: @Html.Raw(ViewBag.ManagerEmployeeData)
      }]
  });
        managerAndEmployeesChart.render();



        // Employee Forms Chart
        var employeeFormChart = new CanvasJS.Chart("employeeFormsChart", {
            theme: "light",
            exportEnabled: true,
            animationEnabled: true,
            title: {
                text: "Number of Forms Submitted by Employees"
            },
            data: [{
                type: "column",
                toolTipContent: "<b>{label}</b>: {y}",
                dataPoints: @Html.Raw(ViewBag.EmployeeFormData)
            }]
        });
        employeeFormChart.render();

     var dailyExpenseChart = new CanvasJS.Chart("dailyExpenseChart", {
            theme: "light",
            exportEnabled: true,
            animationEnabled: true,
            title: {
                text: "Total Expenses by Date"
            },
            axisX: {
                title: "Date"
            },
            axisY: {
                title: "Total Amount",
                prefix: ""
            },
            data: [{
                type: "line",
                toolTipContent: "<b>{label}</b>: {y}",
                dataPoints: @Html.Raw(ViewBag.DailyExpenseData)
            }]
        });
        dailyExpenseChart.render();

         var dailyExpenseChartByCurrency = new CanvasJS.Chart("dailyExpenseChartByCurrency", {
        theme: "light",
        exportEnabled: true,
        animationEnabled: true,
        title: {
            text: "Total Expenses by Currency"
        },
        axisX: {
            title: "Currency"
        },
        axisY: {
            title: "Total Amount",
            prefix: ""
        },
        data: [{
            type: "line",
            toolTipContent: "<b>{label}</b>: {y}",
            dataPoints: @Html.Raw(ViewBag.dailyExpensesByCurrencyDataPoints)
        }]
    });
        dailyExpenseChartByCurrency.render();

    </script>

}

Views/Home/Index.cshtml
@model IEnumerable<ExpenseApplication.Models.ExpenseForm>

@{
    ViewBag.Title = "Home Page";
}

@*Employee Home Page*@

<main>
    <h1>Your Expense Forms</h1>
</main>

@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{
    <div class="form-group row">
        <div class="col-md-2">
            <label for="DateSubmitted">Date Submitted:</label>
            <input type="date" name="DateSubmitted" id="DateSubmitted" class="form-control" value="@Request.QueryString["DateSubmitted"]" />
        </div>
        <div class="col-md-2">
            <label for="Status">Status:</label>
            <select name="Status" id="Status" class="form-control">
                <option value="">-- Select Status --</option>
                <option value="Approved" @(Request.QueryString["Status"] == "Approved" ? "selected" : "")>Approved</option>
                <option value="PendingApproval" @(Request.QueryString["Status"] == "PendingApproval" ? "selected" : "")>Pending Approval</option>
                <option value="Paid" @(Request.QueryString["Status"] == "Paid" ? "selected" : "")>Paid</option>
                <option value="Rejected" @(Request.QueryString["Status"] == "Rejected" ? "selected" : "")>Rejected</option>
            </select>
        </div>
  
        <div class="col-md-2 align-self-end">
            <button type="submit" class="btn btn-primary btn-block">Search</button>
        </div>
    </div>
}

<table class="table table-bordered table-responsive mt-4">
    <thead>
        <tr class="text-center">
            <th>Date Submitted</th>
            <th>Currency</th>
            <th>Status</th>
            <th>Total Amount</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var form in Model)
            {
                <tr class="text-center">
                    <td>@form.DateSubmitted.ToString("dd-MMM-yyyy")</td>
                    <td>@form.Currency</td>
                    <td>
                        <p class="fs-6">
                            @switch (form.Status)
                            {
                                case ExpenseFormStatus.Approved:
                                    <span class="badge text-bg-success">Approved</span>
                                    break;
                                case ExpenseFormStatus.PendingApproval:
                                    <span class="badge text-bg-dark">Pending Approval</span>
                                    break;
                                case ExpenseFormStatus.Paid:
                                    <span class="badge text-bg-primary">Paid</span>
                                    break;
                                case ExpenseFormStatus.Rejected:
                                    <span class="badge text-bg-danger">Rejected</span>
                                    break;
                                default:
                                    <span class="badge badge-secondary">@form.Status</span>
                                    break;
                            }
                        </p>
                    </td>
                    <td>@form.TotalAmount</td>
                    <td>
                        @Html.ActionLink("View Details", "ExpenseDetails", "Employee", new { id = form.Id }, new {@class="btn btn-warning btn-sm"})
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="7">No expense forms found.</td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    <script>
        $(document).ready(function () {
            var message = '@TempData["SweetAlertMessage"]';
            var type = '@TempData["SweetAlertType"]';

            if (message && type) {
                Swal.fire({
                    icon: type,
                    title: message,
                    showConfirmButton: true
                });
            }
        });
    </script>
}

Views/Home/ManagerHome.cshtml
@using System.Web.Mvc
@model IEnumerable<ExpenseApplication.Models.User>
@{
    ViewBag.Title = "ManagerHome";
}

@*If Manager has enployees assign, then only show this button*@
@if (Model.Count() > 0)
{
    <div class="float-end">@Html.ActionLink("Expense Forms", "ExpenseForms", "Manager", new { id = Session["UserId"] }, new { @class = "btn btn-primary" })</div>

}



<h2>Employees Managed by You</h2>

<table class="table table-bordered mt-4">
    <thead>
        <tr>
            <th>Username</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.Username</td>
                <td>@employee.Email</td>
            </tr>
        }
    </tbody>
</table>

Views/Home/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2>Page Not found</h2>